name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile TypeScript file with Deno
        run: deno run build

      - name: Archive Build Artifact
        run: |
          mkdir -p release
          mv ./start ./release/hydrafiles

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-app
          path: ./release/

      - name: Get Version Number
        id: get_version
        run: |
          if [[ "${{ github.event.pull_request }}" != "null" ]]; then
            echo "version=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          else
            echo "version=default-version" >> $GITHUB_ENV
          fi

      - name: Create Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.version }}
          git push origin ${{ env.version }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ env.version }}
          tag: ${{ env.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./release/hydrafiles"
          allowUpdates: true
