name: Deno Compile Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile TypeScript file with Deno
        run: deno run build

      - name: Archive Build Artifact
        run: |
          mkdir -p release
          mv ./start ./release/hydrafiles

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-app
          path: ./release/

      - name: Get PR Title
        id: get_pr_title
        run: |
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            pr_title="${{ github.event.pull_request.title }}"
            echo "PR Title: $pr_title"
            echo "version=$pr_title" >> $GITHUB_ENV
          fi

      - name: Create Tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.version }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ env.version }}
          tag: ${{ env.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./release/hydrafiles"
          allowUpdates: true
