name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile TypeScript file with Deno
        run: deno run build

      - name: Archive Build Artifact
        run: |
          mkdir -p release
          mv ./start ./release/hydrafiles

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-app
          path: ./release/

      - name: Get Version Number from deno.jsonc
        id: get_version
        run: |
          VERSION=$(deno eval 'console.log(JSON.parse(Deno.readTextFileSync("deno.jsonc")).version)')
          echo "VERSION=$VERSION"
          echo "::set-output name=version::$VERSION"

      - name: log
        run: echo "Version ${{ steps.get_version.outputs.version }}"

      - name: Create Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.get_version.outputs.version }}
          git push origin ${{ steps.get_version.outputs.version }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.get_version.outputs.version }}
          tag: ${{ steps.get_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./release/hydrafiles"
          allowUpdates: true
