name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Test
        run: deno run test

      - name: Build
        run: deno run build

      - name: Archive Build Artifact
        run: |
          mkdir -p release
          mv ./start ./release/hydrafiles

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-app
          path: ./release/
